### ISSUE TITLE
CryptographicException at SamFirm.KiesAuth.DecryptNonce(String inp) in KiesAuth.cs

### ISSUE THREAD

**Issue by redddflash** [ivanmeler/SamFirm_Reborn#15]
There seems to be a new issue since today (yesterday it was still working normally), see two examples below. It happens, no matter which region or model is used, or if you just want to check or download a firmware. Tested with version 0.3.6.6 and also with 0.3.6.5.

Maybe Samsung has again changed something in their server authentication?

```
D:\SamFirm>SamFirm_Reborn_0.3.6.6\SamFirm.exe -c -model SM-S918B -region EUX
========== SamFirm Firmware Update Check ==========

Checking firmware for SM-S918B/EUX/S918BXXS3BWKC/S918BOXM3BWJM/S918BXXU3BWJM/S918BXXS3BWKC

Unhandled Exception: System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at SamFirm.KiesAuth.DecryptNonce(String inp) in C:\Users\i_iva\Desktop\SamFirm_Reborn\KiesAuth.cs:line 26.
   at SamFirm.WebRequestExtension.GetResponseFUS(WebRequest wr) in C:\Users\i_iva\Desktop\SamFirm_Reborn\WebRequestExtension.cs:line 20.
   at SamFirm.Web.GenerateNonce() in C:\Users\i_iva\Desktop\SamFirm_Reborn\Web.cs:line 29.
   at SamFirm.Command.UpdateCheck(String model, String region, String pda, String csc, String phone, String data, Boolean BinaryNature, Boolean AutoFetch) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Command.cs:line 68.
   at SamFirm.Command.UpdateCheck(String model, String region, String info, Boolean BinaryNature, Boolean AutoFetch) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Command.cs:line 53.
   at SamFirm.Command.UpdateCheckAuto(String model, String region, Boolean BinaryNature) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Command.cs:line 23.
   at SamFirm.CmdLine.DoCheck() in C:\Users\i_iva\Desktop\SamFirm_Reborn\CmdLine.cs:line 101.
   at SamFirm.CmdLine.ProcessAction() in C:\Users\i_iva\Desktop\SamFirm_Reborn\CmdLine.cs:line 44.
   at SamFirm.Program.Main(String[] args) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Program.cs:line 21.

D:\SamFirm>SamFirm_Reborn_0.3.6.6\SamFirm.exe -c -model SM-G960F -region DBT
========== SamFirm Firmware Update Check ==========

Checking firmware for SM-G960F/DBT/G960FXXUHFVG4/G960FOXMHFVB4/G960FXXUHFVB4/G960FXXUHFVG4

Unhandled Exception: System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at SamFirm.KiesAuth.DecryptNonce(String inp) in C:\Users\i_iva\Desktop\SamFirm_Reborn\KiesAuth.cs:line 26.
   at SamFirm.WebRequestExtension.GetResponseFUS(WebRequest wr) in C:\Users\i_iva\Desktop\SamFirm_Reborn\WebRequestExtension.cs:line 20.
   at SamFirm.Web.GenerateNonce() in C:\Users\i_iva\Desktop\SamFirm_Reborn\Web.cs:line 29.
   at SamFirm.Command.UpdateCheck(String model, String region, String pda, String csc, String phone, String data, Boolean BinaryNature, Boolean AutoFetch) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Command.cs:line 68.
   at SamFirm.Command.UpdateCheck(String model, String region, String info, Boolean BinaryNature, Boolean AutoFetch) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Command.cs:line 53.
   at SamFirm.Command.UpdateCheckAuto(String model, String region, Boolean BinaryNature) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Command.cs:line 23.
   at SamFirm.CmdLine.DoCheck() in C:\Users\i_iva\Desktop\SamFirm_Reborn\CmdLine.cs:line 101.
   at SamFirm.CmdLine.ProcessAction() in C:\Users\i_iva\Desktop\SamFirm_Reborn\CmdLine.cs:line 44.
   at SamFirm.Program.Main(String[] args) in C:\Users\i_iva\Desktop\SamFirm_Reborn\Program.cs:line 21.
```

**Comment by tungtata** [comment]
Samsung just fix the encrypt key and iv so now nonce still got but can not decrypted. Waiting for someone fix it

**Comment by ivanmeler** [comment]
Just as i was working on imporvements.. they change encryption method..
working on it but this might take some time

**Comment by chenxiaolong** [comment]
Switching to the new keys alone isn't sufficient. (They can be found from the same places as the old keys. There's only a tiny bit of obfuscation in the form of two string replacement calls.)

From initial testing, it looks like all of these conditions are necessary:
* New fixed key and flexible key suffixes (reverse engineered)
* Passing additional fields to `/NF_DownloadBinaryInform.do`
  * `CLIENT_PRODUCT` must exist. The value doesn't seem to matter.
     * If this condition isn't met, the server fails with HTTP 500 and returns an HTML response.
  * `CLIENT_VERSION` must exist. The value doesn't seem to matter, but must be non-empty.
    * If this condition isn't met, the server fails with HTTP 500 and returns an HTML response.
  * `DEVICE_IMEI_PUSH` must be set to the target device's IMEI or if the device doesn't have a modem, the serial number.
    *  Invalid IMEIs/serials don't work. Using a valid serial to download firmware for a different device doesn't work. Using a valid serial to download firmware for a different CSC of the same model doesn't work either (unless the same firmware version also exists for the device's original CSC).
    * If this condition isn't met, the server returns a FUS XML response with error code 408.

I'm not sure if it's possible to download arbitrary firmware anymore. I tried various things, like pretending to be old Smart Switch version, with no luck.

**Comment by tungtata** [comment]
> Switching to the new keys alone isn't sufficient. (They can be found from the same places as the old keys. There's only a tiny bit of obfuscation in the form of two string replacement calls.)
> 
> From initial testing, it looks like all of these conditions are necessary:
> 
> * New fixed key and flexible key suffixes (reverse engineered)
> * Passing additional fields to `/NF_DownloadBinaryInform.do`
>   
>   * `CLIENT_PRODUCT` must exist. The value doesn't seem to matter.
>     
>     * If this condition isn't met, the server fails with HTTP 500 and returns an HTML response.
>   * `CLIENT_VERSION` must exist. The value doesn't seem to matter, but must be non-empty.
>     
>     * If this condition isn't met, the server fails with HTTP 500 and returns an HTML response.
>   * `DEVICE_IMEI_PUSH` must be set to the target device's IMEI or if the device doesn't have a modem, the serial number.
>     
>     * Invalid IMEIs/serials don't work. Using a valid serial to download firmware for a different device doesn't work. Using a valid serial to download firmware for a different CSC of the same model doesn't work either (unless the same firmware version also exists for the device's original CSC).
>     * If this condition isn't met, the server returns a FUS XML response with error code 408.
> 
> I'm not sure if it's possible to download arbitrary firmware anymore. I tried various things, like pretending to be old Smart Switch version, with no luck.

Did you got new key of the nonce encrypt?

**Comment by chenxiaolong** [comment]
I won't post the actual keys, but you can run this to extract the keys from publicly available sources: https://gist.github.com/chenxiaolong/62282271bfd8af198b75fc9cce201333

**Comment by tungtata** [comment]
this script works on Mac only right?

**Comment by chenxiaolong** [comment]
No, it should work anywhere where Python is installed (I personally use Linux).

**Comment by tungtata** [comment]
I tried on Windows and got this error
![image](https://github.com/ivanmeler/SamFirm_Reborn/assets/14246681/6ea342cf-6eac-4a85-b0c1-3e9d5ec5ba37)
I am sorry because I don't works with py much

**Comment by chenxiaolong** [comment]
> I tried on Windows and got this error ![image](https://private-user-images.githubusercontent.com/14246681/292088219-6ea342cf-6eac-4a85-b0c1-3e9d5ec5ba37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzM0MjAsIm5iZiI6MTcwMzEzMzEyMCwicGF0aCI6Ii8xNDI0NjY4MS8yOTIwODgyMTktNmVhMzQyY2YtNmVhYy00YTg1LWIwYzEtM2U5ZDVlYzViYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA0MzIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYjhkODZjMzM5ZmZlZmI0YTI0NjIzZWVjZDVkOWZkOTVkZWM5ZDY1MTlhZmY3NGU2ODZiZjIxOGIwMmFiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9sJ4xGknSI9Vf1EBzn6WOSMtqH2jVe5nr9AkMekQLA) I am sorry because I don't works with py much

Thanks, looks like I'm relying on syntax that's only accepted in newer versions of Python. I've updated the script to fix this (replaced `'ASCII'` with `"ASCII"`).

**Comment by tungtata** [comment]
how can I have your private contact bro? like telegram or whatsapp?

**Comment by ivanmeler** [comment]
fixed in new release, will be released in hour or so
